name: bolt_frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.2.3
  http: ^1.6.0
  flutter_secure_storage: ^10.0.0
  jwt_decoder: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-Black.ttf
        - asset: assets/fonts/Outfit-Bold.ttf
        - asset: assets/fonts/Outfit-ExtraBold.ttf
        - asset: assets/fonts/Outfit-ExtraLight.ttf
        - asset: assets/fonts/Outfit-Light.ttf
        - asset: assets/fonts/Outfit-Medium.ttf
        - asset: assets/fonts/Outfit-Regular.ttf
        - asset: assets/fonts/Outfit-SemiBold.ttf
        - asset: assets/fonts/Outfit-Thin.ttf
